// flow-typed signature: 971dbcae1be957f9acbbc79a4135088d
// flow-typed version: <<STUB>>/babel-tape-runner_v2.0.1/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'babel-tape-runner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'babel-tape-runner' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'babel-tape-runner/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'babel-tape-runner/test.js' {
  declare module.exports: $Exports<'babel-tape-runner/test'>;
}
