// flow-typed signature: 2fdfd0081c0820986ccf2f87d03bf2cc
// flow-typed version: <<STUB>>/compressible_v~2.0.10/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'compressible'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'compressible' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'compressible/index' {
  declare module.exports: $Exports<'compressible'>;
}
declare module 'compressible/index.js' {
  declare module.exports: $Exports<'compressible'>;
}
