// flow-typed signature: 66f0318e0c917f1ef695091235af32ba
// flow-typed version: <<STUB>>/eslint-plugin-unicorn_v2.1.2/flow_v0.55.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-unicorn'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-unicorn' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-unicorn/rules/catch-error-name' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/custom-error-definition' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/escape-case' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/explicit-length-check' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/filename-case' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/no-abusive-eslint-disable' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/no-array-instanceof' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/no-hex-escape' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/no-new-buffer' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/no-process-exit' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/number-literal-case' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/prefer-starts-ends-with' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/prefer-type-error' {
  declare module.exports: any;
}

declare module 'eslint-plugin-unicorn/rules/throw-new-error' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-unicorn/index' {
  declare module.exports: $Exports<'eslint-plugin-unicorn'>;
}
declare module 'eslint-plugin-unicorn/index.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn'>;
}
declare module 'eslint-plugin-unicorn/rules/catch-error-name.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/catch-error-name'>;
}
declare module 'eslint-plugin-unicorn/rules/custom-error-definition.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/custom-error-definition'>;
}
declare module 'eslint-plugin-unicorn/rules/escape-case.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/escape-case'>;
}
declare module 'eslint-plugin-unicorn/rules/explicit-length-check.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/explicit-length-check'>;
}
declare module 'eslint-plugin-unicorn/rules/filename-case.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/filename-case'>;
}
declare module 'eslint-plugin-unicorn/rules/no-abusive-eslint-disable.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/no-abusive-eslint-disable'>;
}
declare module 'eslint-plugin-unicorn/rules/no-array-instanceof.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/no-array-instanceof'>;
}
declare module 'eslint-plugin-unicorn/rules/no-hex-escape.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/no-hex-escape'>;
}
declare module 'eslint-plugin-unicorn/rules/no-new-buffer.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/no-new-buffer'>;
}
declare module 'eslint-plugin-unicorn/rules/no-process-exit.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/no-process-exit'>;
}
declare module 'eslint-plugin-unicorn/rules/number-literal-case.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/number-literal-case'>;
}
declare module 'eslint-plugin-unicorn/rules/prefer-starts-ends-with.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/prefer-starts-ends-with'>;
}
declare module 'eslint-plugin-unicorn/rules/prefer-type-error.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/prefer-type-error'>;
}
declare module 'eslint-plugin-unicorn/rules/throw-new-error.js' {
  declare module.exports: $Exports<'eslint-plugin-unicorn/rules/throw-new-error'>;
}
