// flow-typed signature: cd1a344b7f85d2c8e9478f7c6f80d593
// flow-typed version: <<STUB>>/mime-types_v2.1.15/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mime-types'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'mime-types' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mime-types/index' {
  declare module.exports: $Exports<'mime-types'>;
}
declare module 'mime-types/index.js' {
  declare module.exports: $Exports<'mime-types'>;
}
