// flow-typed signature: 4e73ec9ed66e52192661c481b8d0a9f8
// flow-typed version: <<STUB>>/should-http_v0.1.1/flow_v0.46.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'should-http'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'should-http' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'should-http/http-node' {
  declare module.exports: any;
}

declare module 'should-http/http' {
  declare module.exports: any;
}

declare module 'should-http/index-browser' {
  declare module.exports: any;
}

declare module 'should-http/test/http-format' {
  declare module.exports: any;
}

declare module 'should-http/test/http.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'should-http/http-node.js' {
  declare module.exports: $Exports<'should-http/http-node'>;
}
declare module 'should-http/http.js' {
  declare module.exports: $Exports<'should-http/http'>;
}
declare module 'should-http/index-browser.js' {
  declare module.exports: $Exports<'should-http/index-browser'>;
}
declare module 'should-http/index' {
  declare module.exports: $Exports<'should-http'>;
}
declare module 'should-http/index.js' {
  declare module.exports: $Exports<'should-http'>;
}
declare module 'should-http/test/http-format.js' {
  declare module.exports: $Exports<'should-http/test/http-format'>;
}
declare module 'should-http/test/http.test.js' {
  declare module.exports: $Exports<'should-http/test/http.test'>;
}
